#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

[options]
	colorscheme = "gruvbox"
	background = "dark"
	enable_guicolors = true
	default_indent = 4
	github_username = 'nijaru'
	enable_debug = 1
	enable_ale = 1
	# enable_neomake = false
	realtime_leader_guide = 1
	windows_index_type = 3
	search_tools = ["rg", "pt", "ack", "grep", "findstr"]
	bootstrap_before = "myspacevim#before"
	bootstrap_after = "myspacevim#after"
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
	statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
[[layers]]
	name = 'autocomplete'
	auto-completion-return-key-behavior = "complete"
	auto-completion-tab-key-behavior = "smart"
[[layers]]
	name = 'checkers'
	lint_on_the_fly = true
[[layers]]
	name = 'core#statusline'
	enable = true
[[layers]]
	name = 'core#tabline'
	enable = true
[[layers]]
	name = 'colorscheme'
[[layers]]
	name = 'core'
	filetree_show_hidden = true
[[layers]]
	name = 'format'
[[layers]]
	name = 'fzf'
[[layers]]
	name = 'git'
[[layers]]
	name = "lsp"
[[layers]]
	name = 'VersionControl'

[[layers]]
	name = 'lang#c'
[[layers]]
	name = 'lang#go'
[[layers]]
	name = 'lang#haskell'
[[layers]]
	name = 'lang#html'
[[layers]]
	name = 'lang#javascript'
[[layers]]
	name = 'lang#markdown'
[[layers]]
	name = "lang#python"
[[layers]]
	name = "lang#ruby"
[[layers]]
	name = "lang#rust"
	recommended-style = true
[[layers]]
	name = 'lang#sh'
	bash-file-head = [
		'#!/usr/bin/env bash',
		''
	]
[[layers]]
	name = 'lang#toml'
[[layers]]
	name = 'lang#typescript'
[[layers]]
	name = 'lang#vim'

# [[layers]]
#   name = "lsp"
#   filetypes = [
#     "javascript",
#     "python",
#     "ruby",
#     "rust",
#     "sh"
#   ]

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30
