[tools]
age = "latest"
bun = "latest"
go = "latest"
lua = "latest"
node = "latest"
"aqua:nushell/nushell" = "latest"
python = "latest"
ruby = "latest"
shfmt = "latest"
usage = "latest"
zig = "master"

[settings]
idiomatic_version_file_enable_tools = ["python", "true"]
