# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_but_global_optspecs
	string join \n t/trace C/current-dir= f/format= j/json h/help V/version
end

function __fish_but_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_but_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_but_using_subcommand
	set -l cmd (__fish_but_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c but -n "__fish_but_needs_command" -s C -l current-dir -d 'Run as if gitbutler-cli was started in PATH instead of the current working directory' -r -F
complete -c but -n "__fish_but_needs_command" -s f -l format -d 'Explicitly control how output should be formatted' -r -f -a "human\t'The output to write is supposed to be for human consumption, and can be more verbose'
shell\t'The output should be suitable for shells, and assigning the major result to variables so that it can be reused in subsequent CLI invocations'
json\t'Output detailed information as JSON for tool consumption'
none\t'Do not output anything, like redirecting to /dev/null'"
complete -c but -n "__fish_but_needs_command" -s t -l trace -d 'Enable tracing for debug and performance information printed to stderr'
complete -c but -n "__fish_but_needs_command" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_needs_command" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_needs_command" -s V -l version -d 'Print version'
complete -c but -n "__fish_but_needs_command" -a "status" -d 'Overview of the project workspace state.'
complete -c but -n "__fish_but_needs_command" -a "rub" -d 'Combines two entities together to perform an operation like amend, squash, stage, or move.'
complete -c but -n "__fish_but_needs_command" -a "diff" -d 'Displays the diff of changes in the repo.'
complete -c but -n "__fish_but_needs_command" -a "show" -d 'Shows detailed information about a commit or branch.'
complete -c but -n "__fish_but_needs_command" -a "setup" -d 'Sets up a GitButler project from a git repository in the current directory.'
complete -c but -n "__fish_but_needs_command" -a "teardown" -d 'Exit GitButler mode and return to normal Git workflow.'
complete -c but -n "__fish_but_needs_command" -a "pull" -d 'Updates all applied branches to be up to date with the target branch.'
complete -c but -n "__fish_but_needs_command" -a "branch" -d 'Commands for managing branches.'
complete -c but -n "__fish_but_needs_command" -a "worktree" -d 'Commands for managing worktrees.'
complete -c but -n "__fish_but_needs_command" -a "mark" -d 'Mark a commit or branch for auto-stage or auto-commit.'
complete -c but -n "__fish_but_needs_command" -a "unmark" -d 'Removes any marks from the workspace'
complete -c but -n "__fish_but_needs_command" -a "gui" -d 'Open the GitButler GUI for the current project.'
complete -c but -n "__fish_but_needs_command" -a "." -d 'Open the GitButler GUI for the current project.'
complete -c but -n "__fish_but_needs_command" -a "commit" -d 'Commit changes to a stack.'
complete -c but -n "__fish_but_needs_command" -a "push" -d 'Push changes in a branch to remote.'
complete -c but -n "__fish_but_needs_command" -a "reword" -d 'Edit the commit message of the specified commit.'
complete -c but -n "__fish_but_needs_command" -a "oplog" -d 'Commands for viewing and managing operation history.'
complete -c but -n "__fish_but_needs_command" -a "undo" -d 'Undo the last operation by reverting to the previous snapshot.'
complete -c but -n "__fish_but_needs_command" -a "absorb" -d 'Amends changes into the appropriate commits where they belong.'
complete -c but -n "__fish_but_needs_command" -a "discard" -d 'Discard uncommitted changes from the worktree.'
complete -c but -n "__fish_but_needs_command" -a "pr" -d 'Commands for creating and managing pull requests on a forge'
complete -c but -n "__fish_but_needs_command" -a "review" -d 'Commands for creating and managing pull requests on a forge'
complete -c but -n "__fish_but_needs_command" -a "refresh-remote-data" -d 'Trigger a refresh of remote data fetching from the remote, Pull Requests, and CI status.'
complete -c but -n "__fish_but_needs_command" -a "mcp" -d 'AI: Starts up the MCP server.'
complete -c but -n "__fish_but_needs_command" -a "claude" -d 'AI: Claude hooks'
complete -c but -n "__fish_but_needs_command" -a "cursor" -d 'AI: Cursor hooks'
complete -c but -n "__fish_but_needs_command" -a "actions" -d 'INTERNAL: GitButler Actions are automated tasks (like macros) that can be performed on a repository.'
complete -c but -n "__fish_but_needs_command" -a "metrics" -d 'INTERNAL: If metrics are permitted, this subcommand handles posthog event creation.'
complete -c but -n "__fish_but_needs_command" -a "completions" -d 'UTILITY: Generate shell completion scripts for the specified or inferred shell.'
complete -c but -n "__fish_but_needs_command" -a "update" -d 'Manage GitButler CLI and app updates.'
complete -c but -n "__fish_but_needs_command" -a "alias" -d 'Manage command aliases.'
complete -c but -n "__fish_but_needs_command" -a "config" -d 'View and manage GitButler configuration.'
complete -c but -n "__fish_but_needs_command" -a "resolve" -d 'Resolve conflicts in a commit.'
complete -c but -n "__fish_but_needs_command" -a "fetch" -d 'Hidden command that redirects to `but pull --check`'
complete -c but -n "__fish_but_needs_command" -a "squash" -d 'Squash commits together.'
complete -c but -n "__fish_but_needs_command" -a "uncommit" -d 'Uncommit changes from a commit or file-in-commit to the unstaged area.'
complete -c but -n "__fish_but_needs_command" -a "amend" -d 'Amend a file change into a specific commit and rebases any dependent commits.'
complete -c but -n "__fish_but_needs_command" -a "merge" -d 'Merge a branch into your local target branch.'
complete -c but -n "__fish_but_needs_command" -a "move" -d 'Move a commit to a different location in the stack.'
complete -c but -n "__fish_but_needs_command" -a "pick" -d 'Cherry-pick a commit from an unapplied branch into an applied virtual branch.'
complete -c but -n "__fish_but_needs_command" -a "unapply" -d 'Unapply a branch from the workspace.'
complete -c but -n "__fish_but_needs_command" -a "apply" -d 'Apply a branch to the workspace.'
complete -c but -n "__fish_but_needs_command" -a "stage" -d 'Stages a file or hunk to a specific branch.'
complete -c but -n "__fish_but_needs_command" -a "unstage" -d 'Unstages a file or hunk from a branch.'
complete -c but -n "__fish_but_needs_command" -a "skill" -d 'Manage Claude AI skills for GitButler.'
complete -c but -n "__fish_but_needs_command" -a "help" -d 'Show help information grouped by category.'
complete -c but -n "__fish_but_needs_command" -a "onboarding" -d 'INTERNAL: First-run onboarding that shows metrics info and marks onboarding complete'
complete -c but -n "__fish_but_using_subcommand status" -s f -d 'Determines whether the committed files should be shown as well'
complete -c but -n "__fish_but_using_subcommand status" -s v -l verbose -d 'Show verbose output with commit author and timestamp'
complete -c but -n "__fish_but_using_subcommand status" -s r -l refresh-prs -d 'Forces a sync of pull requests from the forge before showing status'
complete -c but -n "__fish_but_using_subcommand status" -s u -l upstream -d 'Show detailed list of upstream commits that haven\'t been integrated yet'
complete -c but -n "__fish_but_using_subcommand status" -l no-hint -d 'Disable hints about available commands at the end of output'
complete -c but -n "__fish_but_using_subcommand status" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand status" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand rub" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand rub" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand diff" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand diff" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand show" -s v -l verbose -d 'Show full commit messages and files changed for each commit'
complete -c but -n "__fish_but_using_subcommand show" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand show" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand setup" -l init -d 'Initialize a new git repository with an empty commit if one doesn\'t exist.'
complete -c but -n "__fish_but_using_subcommand setup" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand setup" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand teardown" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand teardown" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand pull" -s c -l check -d 'Only check the status without updating (equivalent to the old but base check)'
complete -c but -n "__fish_but_using_subcommand pull" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand pull" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand branch; and not __fish_seen_subcommand_from new delete list show" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand branch; and not __fish_seen_subcommand_from new delete list show" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand branch; and not __fish_seen_subcommand_from new delete list show" -f -a "new" -d 'Creates a new branch in the workspace'
complete -c but -n "__fish_but_using_subcommand branch; and not __fish_seen_subcommand_from new delete list show" -f -a "delete" -d 'Deletes a branch from the workspace'
complete -c but -n "__fish_but_using_subcommand branch; and not __fish_seen_subcommand_from new delete list show" -f -a "list" -d 'List the branches in the repository'
complete -c but -n "__fish_but_using_subcommand branch; and not __fish_seen_subcommand_from new delete list show" -f -a "show" -d 'Show commits ahead of base for a specific branch'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from new" -s a -l anchor -d 'Anchor point - either a commit ID or branch name to create the new branch from' -r
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from new" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from new" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from delete" -s f -l force -d 'Force deletion without confirmation'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from delete" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from list" -s l -l local -d 'Show only local branches'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from list" -s r -l remote -d 'Show only remote branches'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from list" -s a -l all -d 'Show all branches (not just active + 20 most recent)'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from list" -l no-ahead -d 'Don\'t calculate and show number of commits ahead of base (faster)'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from list" -l review -d 'Fetch and display review information (PRs, MRs, etc.)'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from list" -l no-check -d 'Don\'t check if each branch merges cleanly into upstream'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from list" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from show" -s r -l review -d 'Fetch and display review information'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from show" -s f -l files -d 'Show files modified in each commit with line counts'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from show" -l ai -d 'Generate AI summary of the branch changes'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from show" -l check -d 'Check if the branch merges cleanly into upstream and identify conflicting commits'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from show" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand branch; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand worktree; and not __fish_seen_subcommand_from new list integrate destroy" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand worktree; and not __fish_seen_subcommand_from new list integrate destroy" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand worktree; and not __fish_seen_subcommand_from new list integrate destroy" -f -a "new" -d 'Create a new worktree from a reference'
complete -c but -n "__fish_but_using_subcommand worktree; and not __fish_seen_subcommand_from new list integrate destroy" -f -a "list" -d 'List all worktrees'
complete -c but -n "__fish_but_using_subcommand worktree; and not __fish_seen_subcommand_from new list integrate destroy" -f -a "integrate" -d 'Integrate a worktree'
complete -c but -n "__fish_but_using_subcommand worktree; and not __fish_seen_subcommand_from new list integrate destroy" -f -a "destroy" -d 'Destroy worktree(s)'
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from new" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from new" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from list" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from integrate" -l target -d 'The target reference to integrate into (defaults to the reference the worktree was created from)' -r
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from integrate" -l dry -d 'Perform a dry run without making changes'
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from integrate" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from integrate" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from destroy" -l reference -d 'Treat the target as a reference instead of a path'
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from destroy" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand worktree; and __fish_seen_subcommand_from destroy" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand mark" -s d -l delete -d 'Deletes a mark'
complete -c but -n "__fish_but_using_subcommand mark" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand mark" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand unmark" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand unmark" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand gui" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand gui" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand ." -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand ." -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand commit; and not __fish_seen_subcommand_from empty" -s m -l message -d 'Commit message' -r
complete -c but -n "__fish_but_using_subcommand commit; and not __fish_seen_subcommand_from empty" -l message-file -d 'Read commit message from file' -r -F
complete -c but -n "__fish_but_using_subcommand commit; and not __fish_seen_subcommand_from empty" -s i -l ai -d 'Generate commit message using AI with optional user summary. Use --ai by itself or --ai="your instructions" (equals sign required for value)' -r
complete -c but -n "__fish_but_using_subcommand commit; and not __fish_seen_subcommand_from empty" -s p -l changes -d 'Uncommitted file or hunk CLI IDs to include in the commit. Can be specified multiple times or as comma-separated values. If not specified, all uncommitted changes (or changes staged to the target branch) are committed' -r
complete -c but -n "__fish_but_using_subcommand commit; and not __fish_seen_subcommand_from empty" -s c -l create -d 'Whether to create a new branch for this commit. If the branch name given matches an existing branch, that branch will be used instead. If no branch name is given, a new branch with a generated name will be created'
complete -c but -n "__fish_but_using_subcommand commit; and not __fish_seen_subcommand_from empty" -s o -l only -d 'Only commit staged files, not unstaged files'
complete -c but -n "__fish_but_using_subcommand commit; and not __fish_seen_subcommand_from empty" -s n -l no-hooks -d 'Bypass pre-commit hooks'
complete -c but -n "__fish_but_using_subcommand commit; and not __fish_seen_subcommand_from empty" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand commit; and not __fish_seen_subcommand_from empty" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand commit; and not __fish_seen_subcommand_from empty" -a "empty" -d 'Insert a blank commit before or after the specified commit.'
complete -c but -n "__fish_but_using_subcommand commit; and __fish_seen_subcommand_from empty" -l before -d 'Insert the blank commit before this commit or branch' -r
complete -c but -n "__fish_but_using_subcommand commit; and __fish_seen_subcommand_from empty" -l after -d 'Insert the blank commit after this commit or branch' -r
complete -c but -n "__fish_but_using_subcommand commit; and __fish_seen_subcommand_from empty" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand commit; and __fish_seen_subcommand_from empty" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand push" -s a -l hashtag -d 'Add hashtag(s) to change (Gerrit). Can be used multiple times' -r
complete -c but -n "__fish_but_using_subcommand push" -s t -l topic -d 'Add custom topic to change (Gerrit). At most one topic can be set' -r
complete -c but -n "__fish_but_using_subcommand push" -s f -l with-force -d 'Force push even if it\'s not fast-forward'
complete -c but -n "__fish_but_using_subcommand push" -s s -l skip-force-push-protection -d 'Skip force push protection checks'
complete -c but -n "__fish_but_using_subcommand push" -s r -l run-hooks -d 'Run pre-push hooks'
complete -c but -n "__fish_but_using_subcommand push" -s w -l wip -d 'Mark change as work-in-progress (Gerrit). Mutually exclusive with --ready'
complete -c but -n "__fish_but_using_subcommand push" -s y -l ready -d 'Mark change as ready for review (Gerrit). This is the default state'
complete -c but -n "__fish_but_using_subcommand push" -l tb -d 'Use branch name as topic (Gerrit)'
complete -c but -n "__fish_but_using_subcommand push" -s p -l private -d 'Mark change as private (Gerrit)'
complete -c but -n "__fish_but_using_subcommand push" -s d -l dry-run -d 'Show what would be pushed without actually pushing'
complete -c but -n "__fish_but_using_subcommand push" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand push" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand reword" -s m -l message -d 'The new commit message or branch name. If not provided, opens an editor' -r
complete -c but -n "__fish_but_using_subcommand reword" -s f -l format -d 'Format the existing commit message to 72-char line wrapping without opening an editor'
complete -c but -n "__fish_but_using_subcommand reword" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand reword" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand oplog; and not __fish_seen_subcommand_from list snapshot restore" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand oplog; and not __fish_seen_subcommand_from list snapshot restore" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand oplog; and not __fish_seen_subcommand_from list snapshot restore" -f -a "list" -d 'List operation history.'
complete -c but -n "__fish_but_using_subcommand oplog; and not __fish_seen_subcommand_from list snapshot restore" -f -a "snapshot" -d 'Create an on-demand snapshot with optional message'
complete -c but -n "__fish_but_using_subcommand oplog; and not __fish_seen_subcommand_from list snapshot restore" -f -a "restore" -d 'Restore to a specific oplog snapshot.'
complete -c but -n "__fish_but_using_subcommand oplog; and __fish_seen_subcommand_from list" -l since -d 'Start from this oplog SHA instead of the head' -r
complete -c but -n "__fish_but_using_subcommand oplog; and __fish_seen_subcommand_from list" -s s -l snapshot -d 'Show only on-demand snapshot entries'
complete -c but -n "__fish_but_using_subcommand oplog; and __fish_seen_subcommand_from list" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand oplog; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand oplog; and __fish_seen_subcommand_from snapshot" -s m -l message -d 'Message to include with the snapshot' -r
complete -c but -n "__fish_but_using_subcommand oplog; and __fish_seen_subcommand_from snapshot" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand oplog; and __fish_seen_subcommand_from snapshot" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand oplog; and __fish_seen_subcommand_from restore" -s f -l force -d 'Skip confirmation prompt'
complete -c but -n "__fish_but_using_subcommand oplog; and __fish_seen_subcommand_from restore" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand oplog; and __fish_seen_subcommand_from restore" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand undo" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand undo" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand absorb" -l dry-run -d 'Show the absorption plan without making any changes'
complete -c but -n "__fish_but_using_subcommand absorb" -s n -l new -d 'Create new commits, instead of amending existing ones. This is useful when you want to preserve existing commits and add new ones for the absorbed changes'
complete -c but -n "__fish_but_using_subcommand absorb" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand absorb" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand discard" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand discard" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand pr; and not __fish_seen_subcommand_from new template" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand pr; and not __fish_seen_subcommand_from new template" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand pr; and not __fish_seen_subcommand_from new template" -f -a "new" -d 'Create a new pull request for a branch. If no branch is specified, you will be prompted to select one. If there is only one branch without a PR, you will be asked to confirm'
complete -c but -n "__fish_but_using_subcommand pr; and not __fish_seen_subcommand_from new template" -f -a "template" -d 'Configure the template to use for PR descriptions. This will list all available templates found in the repository and allow you to select one'
complete -c but -n "__fish_but_using_subcommand pr; and __fish_seen_subcommand_from new" -s m -l message -d 'PR title and description. The first line is the title, the rest is the description' -r
complete -c but -n "__fish_but_using_subcommand pr; and __fish_seen_subcommand_from new" -s F -l file -d 'Read PR title and description from file. The first line is the title, the rest is the description' -r -F
complete -c but -n "__fish_but_using_subcommand pr; and __fish_seen_subcommand_from new" -s f -l with-force -d 'Force push even if it\'s not fast-forward (defaults to true)'
complete -c but -n "__fish_but_using_subcommand pr; and __fish_seen_subcommand_from new" -s s -l skip-force-push-protection -d 'Skip force push protection checks'
complete -c but -n "__fish_but_using_subcommand pr; and __fish_seen_subcommand_from new" -s r -l run-hooks -d 'Run pre-push hooks (defaults to true)'
complete -c but -n "__fish_but_using_subcommand pr; and __fish_seen_subcommand_from new" -s t -l default -d 'Use the default content for the PR title and description, skipping any prompts. If the branch contains only a single commit, the commit message will be used'
complete -c but -n "__fish_but_using_subcommand pr; and __fish_seen_subcommand_from new" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand pr; and __fish_seen_subcommand_from new" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand pr; and __fish_seen_subcommand_from template" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand pr; and __fish_seen_subcommand_from template" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand review; and not __fish_seen_subcommand_from new template" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand review; and not __fish_seen_subcommand_from new template" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand review; and not __fish_seen_subcommand_from new template" -f -a "new" -d 'Create a new pull request for a branch. If no branch is specified, you will be prompted to select one. If there is only one branch without a PR, you will be asked to confirm'
complete -c but -n "__fish_but_using_subcommand review; and not __fish_seen_subcommand_from new template" -f -a "template" -d 'Configure the template to use for PR descriptions. This will list all available templates found in the repository and allow you to select one'
complete -c but -n "__fish_but_using_subcommand review; and __fish_seen_subcommand_from new" -s m -l message -d 'PR title and description. The first line is the title, the rest is the description' -r
complete -c but -n "__fish_but_using_subcommand review; and __fish_seen_subcommand_from new" -s F -l file -d 'Read PR title and description from file. The first line is the title, the rest is the description' -r -F
complete -c but -n "__fish_but_using_subcommand review; and __fish_seen_subcommand_from new" -s f -l with-force -d 'Force push even if it\'s not fast-forward (defaults to true)'
complete -c but -n "__fish_but_using_subcommand review; and __fish_seen_subcommand_from new" -s s -l skip-force-push-protection -d 'Skip force push protection checks'
complete -c but -n "__fish_but_using_subcommand review; and __fish_seen_subcommand_from new" -s r -l run-hooks -d 'Run pre-push hooks (defaults to true)'
complete -c but -n "__fish_but_using_subcommand review; and __fish_seen_subcommand_from new" -s t -l default -d 'Use the default content for the PR title and description, skipping any prompts. If the branch contains only a single commit, the commit message will be used'
complete -c but -n "__fish_but_using_subcommand review; and __fish_seen_subcommand_from new" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand review; and __fish_seen_subcommand_from new" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand review; and __fish_seen_subcommand_from template" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand review; and __fish_seen_subcommand_from template" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand refresh-remote-data" -l fetch -d 'Whether to also refresh git fetch from the remote'
complete -c but -n "__fish_but_using_subcommand refresh-remote-data" -l pr -d 'Whether to also refresh Pull Requests from the forge'
complete -c but -n "__fish_but_using_subcommand refresh-remote-data" -l ci -d 'Whether to also refresh CI status from the forge'
complete -c but -n "__fish_but_using_subcommand refresh-remote-data" -l updates -d 'Whether to also check for application updates'
complete -c but -n "__fish_but_using_subcommand refresh-remote-data" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand refresh-remote-data" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand mcp" -s i -l internal -d 'Starts the internal MCP server which has more granular tools'
complete -c but -n "__fish_but_using_subcommand mcp" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand mcp" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand claude; and not __fish_seen_subcommand_from pre-tool post-tool stop last" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand claude; and not __fish_seen_subcommand_from pre-tool post-tool stop last" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand claude; and not __fish_seen_subcommand_from pre-tool post-tool stop last" -f -a "pre-tool"
complete -c but -n "__fish_but_using_subcommand claude; and not __fish_seen_subcommand_from pre-tool post-tool stop last" -f -a "post-tool"
complete -c but -n "__fish_but_using_subcommand claude; and not __fish_seen_subcommand_from pre-tool post-tool stop last" -f -a "stop"
complete -c but -n "__fish_but_using_subcommand claude; and not __fish_seen_subcommand_from pre-tool post-tool stop last" -f -a "last" -d 'Get the last user message (for testing purposes)'
complete -c but -n "__fish_but_using_subcommand claude; and __fish_seen_subcommand_from pre-tool" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand claude; and __fish_seen_subcommand_from pre-tool" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand claude; and __fish_seen_subcommand_from post-tool" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand claude; and __fish_seen_subcommand_from post-tool" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand claude; and __fish_seen_subcommand_from stop" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand claude; and __fish_seen_subcommand_from stop" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand claude; and __fish_seen_subcommand_from last" -s o -l offset -d 'Offset to skip N most recent messages (positive integer)' -r
complete -c but -n "__fish_but_using_subcommand claude; and __fish_seen_subcommand_from last" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand claude; and __fish_seen_subcommand_from last" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand cursor; and not __fish_seen_subcommand_from after-edit stop" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand cursor; and not __fish_seen_subcommand_from after-edit stop" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand cursor; and not __fish_seen_subcommand_from after-edit stop" -f -a "after-edit"
complete -c but -n "__fish_but_using_subcommand cursor; and not __fish_seen_subcommand_from after-edit stop" -f -a "stop"
complete -c but -n "__fish_but_using_subcommand cursor; and __fish_seen_subcommand_from after-edit" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand cursor; and __fish_seen_subcommand_from after-edit" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand cursor; and __fish_seen_subcommand_from stop" -l nightly
complete -c but -n "__fish_but_using_subcommand cursor; and __fish_seen_subcommand_from stop" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand cursor; and __fish_seen_subcommand_from stop" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand actions; and not __fish_seen_subcommand_from handle-changes" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand actions; and not __fish_seen_subcommand_from handle-changes" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand actions; and not __fish_seen_subcommand_from handle-changes" -f -a "handle-changes" -d 'Automatically handles the changes in the repository, creating a commit with the provided context'
complete -c but -n "__fish_but_using_subcommand actions; and __fish_seen_subcommand_from handle-changes" -s d -l description -l description -d 'A context describing the changes that are currently uncommitted' -r
complete -c but -n "__fish_but_using_subcommand actions; and __fish_seen_subcommand_from handle-changes" -l handler -d 'Which handler is to be used for the operation. Different handles would have different behavior' -r -f -a "simple\t'Handles changes in a simple way'"
complete -c but -n "__fish_but_using_subcommand actions; and __fish_seen_subcommand_from handle-changes" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand actions; and __fish_seen_subcommand_from handle-changes" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand metrics" -l command-name -r -f -a "init\t''
absorb\t''
discard\t''
status\t''
stf\t''
rub\t''
diff\t''
show\t''
commit\t''
commit-empty\t''
push\t''
reword\t''
oplog-list\t''
oplog-snapshot\t''
restore\t''
undo\t''
gui\t''
base-fetch\t''
base-check\t''
pull\t''
branch-new\t''
branch-delete\t''
branch-list\t''
branch-show\t''
branch-unapply\t''
branch-apply\t''
claude-pre-tool\t''
claude-post-tool\t''
claude-stop\t''
cursor-after-edit\t''
cursor-stop\t''
worktree\t''
mark\t''
unmark\t''
forge-auth\t''
forge-list-users\t''
forge-forget\t''
pr-new\t''
pr-template\t''
completions\t''
alias-check\t''
alias-add\t''
alias-remove\t''
refresh-remote-data\t''
resolve\t''
update\t''
merge\t''
skill-install\t''
skill-check\t''
pick\t''
unknown\t''"
complete -c but -n "__fish_but_using_subcommand metrics" -l props -r
complete -c but -n "__fish_but_using_subcommand metrics" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand metrics" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand completions" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand completions" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand update; and not __fish_seen_subcommand_from check suppress install" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand update; and not __fish_seen_subcommand_from check suppress install" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand update; and not __fish_seen_subcommand_from check suppress install" -f -a "check" -d 'Check if a new version of the GitButler CLI is available'
complete -c but -n "__fish_but_using_subcommand update; and not __fish_seen_subcommand_from check suppress install" -f -a "suppress" -d 'Suppress update notifications temporarily'
complete -c but -n "__fish_but_using_subcommand update; and not __fish_seen_subcommand_from check suppress install" -f -a "install" -d 'Install or update the GitButler desktop application (macOS only)'
complete -c but -n "__fish_but_using_subcommand update; and __fish_seen_subcommand_from check" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand update; and __fish_seen_subcommand_from check" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand update; and __fish_seen_subcommand_from suppress" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand update; and __fish_seen_subcommand_from suppress" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand update; and __fish_seen_subcommand_from install" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand update; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand alias; and not __fish_seen_subcommand_from list add remove" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand alias; and not __fish_seen_subcommand_from list add remove" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand alias; and not __fish_seen_subcommand_from list add remove" -f -a "list" -d 'List all configured aliases (default)'
complete -c but -n "__fish_but_using_subcommand alias; and not __fish_seen_subcommand_from list add remove" -f -a "add" -d 'Add a new alias'
complete -c but -n "__fish_but_using_subcommand alias; and not __fish_seen_subcommand_from list add remove" -f -a "remove" -d 'Remove an existing alias'
complete -c but -n "__fish_but_using_subcommand alias; and __fish_seen_subcommand_from list" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand alias; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand alias; and __fish_seen_subcommand_from add" -s g -l global -d 'Store the alias globally (in ~/.gitconfig) instead of locally'
complete -c but -n "__fish_but_using_subcommand alias; and __fish_seen_subcommand_from add" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand alias; and __fish_seen_subcommand_from add" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand alias; and __fish_seen_subcommand_from remove" -s g -l global -d 'Remove from global config (in ~/.gitconfig) instead of local'
complete -c but -n "__fish_but_using_subcommand alias; and __fish_seen_subcommand_from remove" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand alias; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand config; and not __fish_seen_subcommand_from user forge target metrics" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand config; and not __fish_seen_subcommand_from user forge target metrics" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand config; and not __fish_seen_subcommand_from user forge target metrics" -f -a "user" -d 'View and configure user information (name, email, editor)'
complete -c but -n "__fish_but_using_subcommand config; and not __fish_seen_subcommand_from user forge target metrics" -f -a "forge" -d 'View and manage forge configuration'
complete -c but -n "__fish_but_using_subcommand config; and not __fish_seen_subcommand_from user forge target metrics" -f -a "target" -d 'View or set the target branch'
complete -c but -n "__fish_but_using_subcommand config; and not __fish_seen_subcommand_from user forge target metrics" -f -a "metrics" -d 'View or set metrics collection'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from user" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from user" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from user" -f -a "set" -d 'Set a user configuration value'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from user" -f -a "unset" -d 'Unset (remove) a user configuration value'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from forge" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from forge" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from forge" -f -a "auth" -d 'Authenticate with your forge provider (currently only GitHub is supported)'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from forge" -f -a "list-users" -d 'List authenticated forge accounts known to GitButler'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from forge" -f -a "forget" -d 'Forget a previously authenticated forge account'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from target" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from target" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from metrics" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand config; and __fish_seen_subcommand_from metrics" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand resolve; and not __fish_seen_subcommand_from status finish cancel" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand resolve; and not __fish_seen_subcommand_from status finish cancel" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand resolve; and not __fish_seen_subcommand_from status finish cancel" -a "status" -d 'Show the status of conflict resolution, listing remaining conflicted files'
complete -c but -n "__fish_but_using_subcommand resolve; and not __fish_seen_subcommand_from status finish cancel" -a "finish" -d 'Finalize conflict resolution and return to workspace mode'
complete -c but -n "__fish_but_using_subcommand resolve; and not __fish_seen_subcommand_from status finish cancel" -a "cancel" -d 'Cancel conflict resolution and return to workspace mode'
complete -c but -n "__fish_but_using_subcommand resolve; and __fish_seen_subcommand_from status" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand resolve; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand resolve; and __fish_seen_subcommand_from finish" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand resolve; and __fish_seen_subcommand_from finish" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand resolve; and __fish_seen_subcommand_from cancel" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand resolve; and __fish_seen_subcommand_from cancel" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand fetch" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand fetch" -s h -l help -d 'Print help'
complete -c but -n "__fish_but_using_subcommand squash" -s m -l message -d 'Provide a new commit message for the resulting commit' -r
complete -c but -n "__fish_but_using_subcommand squash" -s i -l ai -d 'Generate commit message using AI with optional user summary or instructions. Use --ai by itself or --ai="your instructions" (equals sign required for value)' -r
complete -c but -n "__fish_but_using_subcommand squash" -s d -l drop-message -d 'Drop source commit messages and keep only the target commit\'s message'
complete -c but -n "__fish_but_using_subcommand squash" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand squash" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand uncommit" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand uncommit" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand amend" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand amend" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand merge" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand merge" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand move" -s a -l after -d 'Move the commit after (above) the target instead of before (below)'
complete -c but -n "__fish_but_using_subcommand move" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand move" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand pick" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand pick" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand unapply" -s f -l force -d 'Force unapply without confirmation'
complete -c but -n "__fish_but_using_subcommand unapply" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand unapply" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand apply" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand apply" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand stage" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand stage" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand unstage" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand unstage" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand skill; and not __fish_seen_subcommand_from install check" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand skill; and not __fish_seen_subcommand_from install check" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand skill; and not __fish_seen_subcommand_from install check" -f -a "install" -d 'Install the GitButler CLI skill files for Coding agents'
complete -c but -n "__fish_but_using_subcommand skill; and not __fish_seen_subcommand_from install check" -f -a "check" -d 'Check if installed GitButler skills are up to date with the CLI version'
complete -c but -n "__fish_but_using_subcommand skill; and __fish_seen_subcommand_from install" -s p -l path -d 'Custom path where to install the skill (relative to repository root or absolute)' -r
complete -c but -n "__fish_but_using_subcommand skill; and __fish_seen_subcommand_from install" -s g -l global -d 'Install the skill globally instead of in the current repository'
complete -c but -n "__fish_but_using_subcommand skill; and __fish_seen_subcommand_from install" -s d -l detect -d 'Automatically detect where to install by finding existing installation'
complete -c but -n "__fish_but_using_subcommand skill; and __fish_seen_subcommand_from install" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand skill; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand skill; and __fish_seen_subcommand_from check" -s g -l global -d 'Only check global installations (in home directory)'
complete -c but -n "__fish_but_using_subcommand skill; and __fish_seen_subcommand_from check" -s l -l local -d 'Only check local installations (in current repository)'
complete -c but -n "__fish_but_using_subcommand skill; and __fish_seen_subcommand_from check" -s u -l update -d 'Automatically update any outdated skills found'
complete -c but -n "__fish_but_using_subcommand skill; and __fish_seen_subcommand_from check" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand skill; and __fish_seen_subcommand_from check" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand help" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c but -n "__fish_but_using_subcommand onboarding" -s j -l json -d 'Whether to use JSON output format'
complete -c but -n "__fish_but_using_subcommand onboarding" -s h -l help -d 'Print help (see more with \'--help\')'
